master:
  installPlugins:
  - kubernetes:1.12.6
  - workflow-job:2.24
  - workflow-aggregator:2.5
  - credentials-binding:1.16
  - git:3.9.1
  - google-oauth-plugin:0.6
  - google-source-plugin:0.3
  cpu: "1"
  memory: "3500Mi"
  javaOpts: "-Xms3500m -Xmx3500m"
  serviceType: LoadBalancer
agent:
  enabled: false
persistence:
  size: 100Gi
networkPolicy:
  ApiVersion: networking.k8s.io/v1
rbac:
  create: true
  serviceAccount:
    name: cd-jenkins




